import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Hero from "@/components/Landingpage/Hero";
import AppointmentContextProvider from "@/context/AppointmentContext";
import ContactUsClient from "@/components/ContactUsClient";

const roboto = Roboto({ subsets: ["latin"], weight: ["300", "400", "500", "700"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col ${roboto.className}`}>
        <AppointmentContextProvider>
          <Header />
          <main className="flex-grow">
            <ContactUsClient />
            {children}
            </main>
          <Footer />
        </AppointmentContextProvider>
      </body>
    </html>
  );
}
