export const citiesInPakistan = [
    "Karachi",
    "Lahore",
    "Faisalabad",
    "Rawalpindi",
    "Gujranwala",
    "Peshawar",
    "Multan",
    "Saidu Sharif",
    "Quetta",
    "Islamabad",
    "Bahawalpur",
    "Sargodha",
    "Sialkot City",
    "Sukkur",
    "Larkana",
    "Chiniot",
    "Sheikhupura",
    "Jhang City",
    "Dera Ghazi Khan",
    "Gujrat",
    "Rahimyar Khan",
    "Kasur",
    "Mardan",
    "Mingaora",
    "Nawabshah",
    "Sahiwal",
    "Mirpur Khas",
    "Okara",
    "Mandi Burewala",
    "Jacobabad",
    "Saddiqabad",
    "Kohat",
    "Muridke",
    "Muzaffargarh",
    "Khanpur",
    "Gojra",
    "Mandi Bahauddin",
    "Abbottabad",
    "Turbat",
    "Dadu",
    "Bahawalnagar",
    "Khuzdar",
    "Pakpattan",
    "Tando Allahyar",
    "Vihari",
    "Jaranwala",
    "Kamalia",
    "Kot Addu",
    "Nowshera",
    "Swabi",
    "Dera Ismail Khan",
    "Chaman",
    "Parachinar",
    "Gwadar",
    "Kundian",
    "Shahdadkot",
    "Haripur",
    "Pattoki",
    "Badin",
    "Lodhran",
    "Hafizabad",
    "Charsadda",
    "Mansehra",
    "Mianwali",
    "Mirpur Bhtoro",
    "Shikarpur",
    "Attock Khurd",
    "Batgram",
    "Matiari",
    "Ghotki",
    "Naushahro Firoz",
    "Alipur",
    "Tando Muhammad Khan",
    "Jampur",
    "Zhob",
    "Kotri",
    "Khairpur Mir’s",
    "Khushab",
    "Bajaur",
    "Kharan",
    "Shahdadpur",
    "Jalalpur Jattan",
    "Bannu",
    "Moro",
    "Toba Tek Singh",
    "Jatoi Shimali",
    "Chilas",
    "Kalat",
    "Kot Malik",
    "Uthal",
    "Nushki",
    "Karak",
    "Risalpur Cantonment",
    "Hazro City",
    "Tank",
    "Hyderabad City",
    "Sanghar",
    "Chakwal",
    "Nankana Sahib",
    "Tando Adam",
    "Khairpur Nathan Shah",
    "Chichawatni",
    "Mailsi",
    "Samundri",
    "Pasrur",
    "Dina",
    "Jhang Sadr",
    "Kamoke",
    "Kotli",
    "Fort Abbas",
    "Pishin",
    "Dera Murad Jamali",
    "Mastung",
    "Kohlu",
    "Sui",
    "Bela",
    "Chowki Jamali",
    "Dadhar",
    "Gandava",
    "Harnai",
    "Hub",
    "Jiwani",
    "Lasbela",
    "Loralai",
    "Mach",
    "Mekhtar",
    "Pasni",
    "Sibi",
    "Sohebatpur",
    "Surab",
    "Usta Mohammad",
    "Washuk",
    "Rawalpindi",
    "Hyderabad",
    "Sialkot"
  ];

 export const countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia (Czech Republic)",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (formerly Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine State",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ];
  